spring:
  datasource:
    node1:
      JdbcUrl: jdbc:mysql://localhost:3316/java_course
      username: root
      password:
      maximumPoolSize: 1
    node2:
      JdbcUrl: jdbc:mysql://localhost:3326/java_course
      username: root
      password:
      maximumPoolSize: 1

