version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "aaaa1234"
      MYSQL_USER: "kxw07"
      MYSQL_PASSWORD: "aaaa1234"
    volumes:
      - /Users/kai/dojo/java/GeekUniversityAdvancedJava/mysql/data:/var/lib/mysql

